version: 2
project_name: mycel
builds:
  -
    id: "mycel"
    binary: "mycel"
    main: ./cmd/mycel
archives:
  -
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Philip Silva
    homepage: https://github.com/psilva261/mycel
    maintainer: Philip Silva <psilva261@github.com>
    description: NA
    license: bsd
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
